blank_issues_enabled: true
contact_links:
  - name: Question
    url: https://github.com/Shannon-Data/ShannonBase/discussions/categories/q-a
    about: Please ask and answer questions on the discussions Q&A category.